sudo: false

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DRF_VERSION=3.5 DATABASE_URL=sqlite://
  - DRF_VERSION=3.5 DATABASE_URL=mysql://root:@localhost/test_db
  - DRF_VERSION=3.5 DATABASE_URL=postgres://postgres@/test_db
  - DRF_VERSION=3.6 DATABASE_URL=sqlite://
  - DRF_VERSION=3.6 DATABASE_URL=mysql://root:@localhost/test_db
  - DRF_VERSION=3.6 DATABASE_URL=postgres://postgres@/test_db

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install tox coveralls python-coveralls psycopg2 mysqlclient

cache: pip

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e flake8; fi

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION-drf$DRF_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

after_success:
  - coveralls

matrix:
  fast_finish: true
